### ISSUE TITLE
 升级的时候报错 Make a mistake at the time of escalation

### ISSUE THREAD

**Issue by juzhijian** [Minecolonies/Rankup#18]
[14:59:23] [Server thread/ERROR] [Sponge]: Could not pass RURankupEvent to Plugin{id=rankup, name=Rankup, version=7922, description=A simple plugin for increasing player ranks based on time, url=http://github.com/Minecolonies/Rankup, source=/data/SpongeServer/./mods/plugins/Rankup-V7922-API7-plugin.jar}
java.lang.NoClassDefFoundError: com/magitechserver/magibridge/MagiBridge
        at com.minecolonies.rankup.modules.magibridge.listeners.MagibridgeListener.onRankup(MagibridgeListener.java:32) ~[MagibridgeListener.class:?]
        at org.spongepowered.common.event.listener.RURankupEventListener_MagibridgeListener_onRankup78.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:420) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) ~[SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3214]
        at com.minecolonies.rankup.util.RankingUtils.rankUp(RankingUtils.java:136) ~[RankingUtils.class:?]
        at com.minecolonies.rankup.util.RankingUtils.timeUp(RankingUtils.java:42) ~[RankingUtils.class:?]
        at com.minecolonies.rankup.modules.timing.TimingModule.playerTimeAdd(TimingModule.java:56) ~[TimingModule.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_171]
        at org.spongepowered.common.scheduler.TaskExecutorService$RepeatableFutureTask.run(TaskExecutorService.java:263) ~[TaskExecutorService$RepeatableFutureTask.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3214]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_171]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2705-7.1.0-BETA-3214]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:325) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3214]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:662) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:597) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[14:59:23] [Server thread/INFO] [nucleus]: Server 执行指令: /luckperms user Xia_Xiaoyu parent add feudallord
[14:59:23] [Server thread/INFO] [nucleus]: Server 执行指令: /say Xia_Xiaoyu joined group feudallord
[14:59:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Server] Xia_Xiaoyu joined group feudallord
[14:59:23] [Server thread/INFO] [nucleus]: Server 执行指令: /give Xia_Xiaoyu minecraft:dirt
[14:59:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Given [Dirt] * 1 to Xia_Xiaoyu
[14:59:23] [Server thread/INFO] [nucleus]: Server 执行指令: /luckperms user Xia_Xiaoyu parent remove vassal

**Comment by Asherslab** [comment]
yes, sadly Chinese characters do not work, that is a Sponge issue.

**Comment by juzhijian** [comment]
What's the impact of this problem?

**Comment by Asherslab** [comment]
The plugin won't work for any users that have Chinese Characters in their name

**Comment by juzhijian** [comment]
Does that have an impact on that place in Chinese?

**Comment by marchermans** [comment]
Yes. Chinese characters require a 32 bit UNICODE to work. which is not supported by Sponge.
