### ISSUE TITLE
wont connect to MySQL server

### ISSUE THREAD

**Issue by Jessasaurus** [Minecolonies/Rankup#22]
12.12 21:04:10 [Server] INFO [rankup]: preInit
12.12 21:04:10 [Server] INFO [rankup]: Starting QuickStart Module Loader version 0.8.2 subsystem.
12.12 21:04:10 [Server] WARN [rankup]: Pre Init failed
12.12 21:04:10 [Server] INFO uk.co.drnaylor.quickstart.exceptions.QuickStartModuleDiscoveryException: Unable to start QuickStart
12.12 21:04:10 [Server] INFO at uk.co.drnaylor.quickstart.ModuleContainer.<init>(ModuleContainer.java:185) ~[ModuleContainer.class:?]
12.12 21:04:10 [Server] INFO at uk.co.drnaylor.quickstart.modulecontainers.DiscoveryModuleContainer.<init>(DiscoveryModuleContainer.java:120) ~[DiscoveryModuleContainer.class:?]
12.12 21:04:10 [Server] INFO at uk.co.drnaylor.quickstart.modulecontainers.DiscoveryModuleContainer.<init>(DiscoveryModuleContainer.java:45) ~[DiscoveryModuleContainer.class:?]
12.12 21:04:10 [Server] INFO at uk.co.drnaylor.quickstart.modulecontainers.DiscoveryModuleContainer$Builder.build(DiscoveryModuleContainer.java:239) ~[DiscoveryModuleContainer$Builder.class:?]
12.12 21:04:10 [Server] INFO at uk.co.drnaylor.quickstart.modulecontainers.DiscoveryModuleContainer$Builder.build(DiscoveryModuleContainer.java:161) ~[DiscoveryModuleContainer$Builder.class:?]
12.12 21:04:10 [Server] INFO at uk.co.drnaylor.quickstart.ModuleContainer$Builder.build(ModuleContainer.java:808) ~[ModuleContainer$Builder.class:?]
12.12 21:04:10 [Server] INFO at com.minecolonies.rankup.Rankup.onPreInit(Rankup.java:120) [Rankup.class:?]
12.12 21:04:10 [Server] INFO at org.spongepowered.common.event.listener.GamePreInitializationEventListener_Rankup_onPreInit55.handle(Unknown Source) [?:?]
12.12 21:04:10 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-7.1.0-BETA-33]
12.12 21:04:10 [Server] INFO at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:408) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
12.12 21:04:10 [Server] INFO at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:435) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
12.12 21:04:10 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-7.1.0-BETA-33]
12.12 21:04:10 [Server] INFO at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:221) [SpongeImpl.class:1.12.2-7.1.0-BETA-33]

**Comment by Asherslab** [comment]
please pass on a gist of your rankup.conf

**Comment by Jessasaurus** [comment]
core {
    # This is the template for the /ru check command, accepted entries are: 
    # {player}        - The Player's name (the one being checked)
    # {rank-next}        - The Player's next rank
    # {rank}          - The current rank of the player
    # {prefix}        - The prefix of the player's current group
    # {timing-time}   - How much time the player has been playing 
    # {timing-next}   - How much time until the player joins the next group 
    # {economy-bal}   - How much money the player has
    # {economy-next}  - How much money the player needs to join the next group
    # {purchase-left}  - How much money will be left after rank purchase
    # {joindate}      - The date of when the player joined your server
    # {lastjoin}      - When the player last joined the server
    # {purchase-button}      - button used to purchase the next rank (needs purchase module)
    # {track}         - The current track of the player.
    check-message=[
        "Â§6---[Â§2{player}Â§6]---",
        "Â§fRank: {rank}",
        "Â§fTrack: {track}",
        "Â§fPlay time: {timing-time}",
        "Â§fTime to next group: {timing-next}",
        "Â§fJoin date: Â§a{joindate}",
        "Â§fLast join: Â§9{lastjoin}",
        "Â§6-----------"
    ]
    # setting for "days" output in time desc
    daysDisplay="day(s)"
    # If true a message will be output to console every time players are updated or checked.
    debug-mode=false
    # This is weird, but basically Luckperms is screwing with something, anyway, please put your BASE group here (luckperms default is "default"
    defaultGroup=default
    # List of disabled groups
    disabled-groups=[
        admin,
        mod,
        owner
    ]
    # The message to display for a player in chat when they login to the server for the first time
    first-time-welcome-message="Welcome to our server {player}!"
    # setting for "hours" output in time desc
    hoursDisplay="hour(s)"
    # setting for "minutes" output in time desc
    minutesDisplay="minute(s)"
    # This is the prefix that will be put in place if a player has no prefix, leave "" to have no prefix fall-back
    prefix-fallback=Default
    # the command the plugin will execute via console to remove a rank from a player, valid entries: {player} and {group}
    rankdown-command="luckperms user {player} parent remove {group}"
    # The command the plugin will execute via console to add a rank to a player, valid entries: {player} and {group}
    rankup-command="luckperms user {player} parent add {group}"
    # Whether to remove all other player groups from player after rankUp (Using "rankdown-command")
    remove-previous-group=true
    # This is where all track config names are defined, please be careful here.
    track-configs=[
        "groups.conf",
        "patreons.conf"
    ]
    # The message to display for a player in chat when they login to the server
    welcome-message="Welcome back {player}, your current rank is {prefix}!"
}
databases {
    # You may choose between MySQL (Mariadb works too) or H2 (Hikari) databases for Player Stats storage!
    database=mysql
    sqlAddress="0.0.0.0:3306"
    sqlDatabase=rankup
    sqlPassword=password
    sqlTablePrefix="rankup_"
    sqlUsername=User
}
magibridge {
    # Message to discord when a player ranks up! 
    # valid entries: {player}, {magibridge-next} and {magibridge-current}
    rankup-Message="Player {player} has left the {magibridge-current} group and joined the {magibridge-next} group! :smile:"
    # Set to true if you want the rankup message sent in the MC-Staff channel instead!
    # (Only possible if Magibridge is set to use Nucleus)
    send-in-staff=true
}
modules {
    databases=ENABLED
    economy=DISABLED
    magibridge=ENABLED
    purchase=DISABLED
    timing=ENABLED
}
timing {
    # Here you may set how you want to have the body of the top command display, accepted entries are same as check-message
    top-message=[
        "Â§6---[Â§2{player}Â§6]---",
        "Â§fRank: {rank}",
        "Â§f{timing-time}",
        "Â§fJoin date: Â§a{joindate}",
        "Â§6-----------"
    ]
    # This is where you may define how the bottom of the top message displays
    top-message-footer="Â§f----------------------------"
    # This is where you may define how the top of the top message displays
    top-message-head="Â§f------{Top Play Times}------"
    # The amount of minutes to pass between timing updates
    update-interval=1
}
SQL ip address, & password removed from the copy

**Comment by Asherslab** [comment]
And that crash is only occurring when you enable the database module?

**Comment by Jessasaurus** [comment]
only when i use the MySQL database

**Comment by Jecvay** [comment]
![QQ图片20190720135053](https://user-images.githubusercontent.com/3610248/61574670-6e8db180-aaf5-11e9-9ad8-760de66f6e94.png)
